apiVersion: apps/v1
kind: Deployment
metadata:
  name:  red-color
spec:
  replicas: 3
  selector:
    matchLabels:
      color: red
  template:
    metadata:
      labels:
        color: red
        tier: color
    spec:
      containers:
        - name: sbeliakou/color:v1
          env:
          - name: COLOR
            value: red
          ports:
          - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  green-color
spec:
  replicas: 1
  selector:
    matchLabels:
      color: green
  template:
    metadata:
      labels:
        color: green
        tier: color
    spec:
      containers:
        - name: sbeliakou/color:v1
          env:
          - name: COLOR
            value: green
          ports:
          - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  yellow-color
spec:
  replicas: 2
  selector:
    matchLabels:
      color: yellow
  template:
    metadata:
      labels:
        color: yellow
        tier: color
    spec:
      containers:
        - name: sbeliakou/color:v1
          env:
          - name: COLOR
            value: yellow
          ports:
          - containerPort: 80